# Generated by Django 4.1.7 on 2023-05-10 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_category_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='image',
            new_name='thumbnail',
        ),
    ]
