# Generated by Django 4.1.7 on 2023-05-10 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_rename_image_category_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='thumbnail',
        ),
    ]
