# Generated by Django 4.1.7 on 2023-05-11 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_category_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
    ]
