# Generated by Django 4.1.7 on 2023-05-17 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_magasin'),
    ]

    operations = [
        migrations.CreateModel(
            name='tast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ('firstname',),
            },
        ),
    ]
