# Generated by Django 4.1.7 on 2023-05-23 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_tast'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tast',
        ),
    ]
