# Generated by Django 4.1.7 on 2023-05-23 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_delete_tast'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Magasin',
        ),
    ]
