# Generated by Django 4.1.7 on 2023-06-06 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_promo', models.CharField(max_length=50)),
                ('pourcentage_reduction', models.FloatField()),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Variation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('Categorie_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.category')),
            ],
            options={
                'ordering': ('nom',),
            },
        ),
        migrations.CreateModel(
            name='Variation_Opt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50)),
                ('variation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.variation')),
            ],
            options={
                'ordering': ('value',),
            },
        ),
        migrations.CreateModel(
            name='Promotion_Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Produit_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.product')),
                ('Promotion_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.promotion')),
            ],
        ),
        migrations.CreateModel(
            name='Produit_Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.article')),
                ('variation_opt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.variation_opt')),
            ],
        ),
    ]
