# Generated by Django 4.1.7 on 2023-06-08 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_promotion_variation_variation_opt_promotion_produit_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='Product',
            new_name='Produit_id',
        ),
    ]
