# Generated by Django 4.1.7 on 2023-06-06 22:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0017_promotion_variation_variation_opt_promotion_produit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantité', models.IntegerField()),
                ('date_commande', models.DateTimeField()),
                ('statut', models.CharField(max_length=255)),
                ('article_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.article')),
            ],
        ),
        migrations.CreateModel(
            name='Compte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_nes', models.DateTimeField(null=True)),
                ('adresse', models.CharField(max_length=255, null=True)),
                ('telephone', models.CharField(max_length=255, null=True)),
                ('typeC', models.CharField(max_length=50, null=True)),
                ('num_ident', models.IntegerField(null=True)),
                ('user', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='mode_de_paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default=1, max_length=255)),
                ('code', models.CharField(max_length=255)),
                ('valeur', models.IntegerField(default=1)),
                ('date_expirée', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Sous_catégorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('parent_cat_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.category')),
            ],
            options={
                'ordering': ('nom',),
            },
        ),
        migrations.CreateModel(
            name='reclamation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=50)),
                ('type_reclm', models.CharField(max_length=50)),
                ('date_reclamation', models.DateTimeField(auto_now_add=True)),
                ('compte_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Comptes.compte')),
            ],
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.IntegerField()),
                ('date_paiement', models.DateTimeField(auto_now_add=True)),
                ('typePaiement', models.CharField(max_length=50)),
                ('commande_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Comptes.commande')),
            ],
        ),
        migrations.CreateModel(
            name='Magasin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('adresse', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=255)),
                ('type_livr', models.CharField(max_length=255)),
                ('categorie_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.category')),
            ],
            options={
                'ordering': ('nom',),
            },
        ),
        migrations.CreateModel(
            name='Livraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_livr', models.CharField(max_length=255)),
                ('adresse_livraison', models.CharField(max_length=255)),
                ('date_livraison', models.DateTimeField(auto_now_add=True)),
                ('commande_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Comptes.commande')),
            ],
        ),
        migrations.CreateModel(
            name='List_Favoris',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.article')),
                ('compte_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Comptes.compte')),
            ],
        ),
        migrations.CreateModel(
            name='Gérant_de_magasin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compte_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Comptes.compte')),
                ('magasin_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Comptes.magasin')),
            ],
            options={
                'ordering': ('compte_id',),
            },
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentaire', models.CharField(max_length=255)),
                ('note', models.IntegerField()),
                ('date_ajoutée', models.DateTimeField(auto_now_add=True)),
                ('article_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.article')),
                ('compte_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Comptes.compte')),
            ],
            options={
                'ordering': ('date_ajoutée',),
            },
        ),
        migrations.CreateModel(
            name='depot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
                ('adresse', models.CharField(max_length=255)),
                ('compte_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Comptes.compte')),
                ('magasin_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Comptes.magasin')),
            ],
            options={
                'ordering': ('compte_id',),
            },
        ),
        migrations.CreateModel(
            name='Demand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Categorie', models.CharField(max_length=255)),
                ('Motivation', models.CharField(max_length=255)),
                ('nom', models.CharField(max_length=255)),
                ('compte_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Comptes.compte')),
            ],
        ),
        migrations.AddField(
            model_name='commande',
            name='compte_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Comptes.compte'),
        ),
    ]
