# Generated by Django 4.1.7 on 2023-06-08 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_rename_product_article_produit_id'),
        ('Comptes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='magasin',
            options={},
        ),
        migrations.RemoveField(
            model_name='magasin',
            name='categorie_id',
        ),
        migrations.AddField(
            model_name='magasin',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='magasins', to='product.category'),
        ),
        migrations.AddField(
            model_name='magasin',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='magasin',
            name='product',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='product.product'),
        ),
        migrations.AddField(
            model_name='magasin',
            name='slug',
            field=models.SlugField(default=''),
        ),
        migrations.AddField(
            model_name='magasin',
            name='thumbnail',
            field=models.ImageField(blank=True, default='uploads/store.png', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='article_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='product.article'),
        ),
        migrations.AlterField(
            model_name='magasin',
            name='telephone',
            field=models.IntegerField(),
        ),
    ]
