# Generated by Django 4.1.7 on 2023-06-08 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_rename_product_article_produit_id'),
        ('Comptes', '0004_remove_magasin_magasin_category_magasin_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='magasin',
            name='category',
        ),
        migrations.AddField(
            model_name='magasin',
            name='magasin_category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='product.category'),
        ),
    ]
